version: "2.2"
services:
  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    networks:
      - owl
    environment:
      POSTGRES_PASSWORD: hoothoo
      POSTGRES_DB: scoring

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - owl

  scoring:
    image: translucentlink/scoring:0.0.24
    restart: always
    platform: linux/amd64
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:hoothoo@db:5432/scoring?sslmode=disable
      - PORT=8080
    ports:
      - 8083:8080
    networks:
      - owl

networks:
  owl:
    driver: bridge