// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Chain struct {
	ID             int         `json:"id"`
	Name           string      `json:"name"`
	RPCURL         string      `json:"rpcUrl"`
	BlockFetchSize int         `json:"blockFetchSize"`
	Protocols      []*Protocol `json:"protocols"`
}

type EventDefn struct {
	ID           int    `json:"id"`
	TopicName    string `json:"topicName"`
	TopicHashHex string `json:"topicHashHex"`
	AbiSignature string `json:"abiSignature"`
}

type NewChain struct {
	Name           string `json:"name"`
	RPCURL         string `json:"rpcUrl"`
	BlockFetchSize int    `json:"blockFetchSize"`
}

type NewEventDefn struct {
	Protocol     string `json:"protocol"`
	TopicName    string `json:"topicName"`
	AbiSignature string `json:"abiSignature"`
}

type NewProtocol struct {
	Name string `json:"name"`
	Abi  string `json:"abi"`
}

type NewProtocolInstance struct {
	Protocol         string `json:"protocol"`
	Chain            string `json:"chain"`
	ContractAddress  string `json:"contractAddress"`
	FirstBlockToRead int    `json:"firstBlockToRead"`
}

type Protocol struct {
	ID              int          `json:"id"`
	Name            string       `json:"name"`
	Abi             string       `json:"abi"`
	ScannableEvents []*EventDefn `json:"scannableEvents"`
}

type ProtocolInstance struct {
	ID               int       `json:"id"`
	Protocol         *Protocol `json:"protocol"`
	Chain            *Chain    `json:"chain"`
	ContractAddress  string    `json:"contractAddress"`
	FirstBlockToRead int       `json:"firstBlockToRead"`
	LastBlockRead    int       `json:"lastBlockRead"`
}
